<!DOCTYPE html>
<html>
<head>
    <title>Psychotest Report - {{ $link->applicant_name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }
        .info-section {
            margin-bottom: 30px;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
        }
        .info-table th {
            text-align: left;
            width: 150px;
            padding: 8px 0;
            color: #666;
        }
        .info-table td {
            padding: 8px 0;
            font-weight: bold;
        }
        .results-section h2 {
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
            font-size: 1.2em;
            color: #444;
        }
        .answer-card {
            margin-bottom: 15px;
            padding: 10px;
            background: #f9f9f9;
            border-radius: 4px;
        }
        .question {
            font-weight: bold;
            margin-bottom: 5px;
        }
        .answer {
            color: #2563eb;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 0.8em;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Psychotest Report</h1>
    </div>

    <div class="info-section">
        <table class="info-table">
            <tr>
                <th>Applicant</th>
                <td>{{ $link->applicant_name }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ $link->applicant_email ?? '-' }}</td>
            </tr>
            <tr>
                <th>Test Date</th>
                <td>{{ $link->finished_at ? $link->finished_at->format('d M Y, H:i') : '-' }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ $duration ?? '-' }}</td>
            </tr>
        </table>
    </div>

    <div class="results-section">
        <h2>Test Results</h2>
        @if($link->results)
            @foreach($link->results as $key => $value)
                <div class="answer-card">
                    <div class="question">Question {{ $key }}</div>
                    <div class="answer">{{ is_array($value) ? implode(', ', $value) : $value }}</div>
                </div>
            @endforeach
        @else
            <p>No answers recorded.</p>
        @endif
    </div>

    <div class="footer">
        Generated by Tako HR System on {{ date('d M Y, H:i') }}
    </div>
</body>
</html>
