<!DOCTYPE html>
<html>
<head>
    <title>Psychotest Report - {{ $link->applicant_name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 10px;
        }
        .info-section {
            margin-bottom: 30px;
        }
        .info-table {
            width: 100%;
            border-collapse: collapse;
        }
        .info-table th {
            text-align: left;
            width: 150px;
            padding: 8px 0;
            color: #666;
        }
        .info-table td {
            padding: 8px 0;
            font-weight: bold;
        }
        .results-section h2 {
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
            font-size: 1.2em;
            color: #444;
        }
        .answer-card {
            margin-bottom: 15px;
            padding: 10px;
            background: #f9f9f9;
            border-radius: 4px;
        }
        .question {
            font-weight: bold;
            margin-bottom: 5px;
        }
        .answer {
            color: #2563eb;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 0.8em;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Psychotest Report</h1>
    </div>

    <div class="info-section">
        <table class="info-table">
            <tr>
                <th>Applicant</th>
                <td>{{ $link->applicant_name }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ $link->applicant_email ?? '-' }}</td>
            </tr>
            <tr>
                <th>Test Date</th>
                <td>{{ $link->finished_at ? $link->finished_at->format('d M Y, H:i') : '-' }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ $duration ?? '-' }}</td>
            </tr>
        </table>
    </div>

    <div class="results-section">
        <h2>Test Results</h2>
        @if($link->results)
            @foreach($link->results as $sessionKey => $sessionData)
                @php
                    $sessionNum = (int) str_replace('session_', '', $sessionKey);
                    $sessionNames = [
                        1 => 'PAPICOSTIC',
                        2 => 'CFIT',
                        3 => 'DISC',
                        4 => 'Skill Test'
                    ];
                    $sessionName = $sessionNames[$sessionNum] ?? "Section $sessionNum";
                @endphp

                <h3 style="margin-top: 20px; color: #6366f1; border-left: 4px solid #6366f1; padding-left: 10px;">{{ $sessionName }}</h3>
                
                @if(isset($sessionData['answers']) && count($sessionData['answers']) > 0)
                    @foreach($sessionData['answers'] as $qId => $answer)
                        <div class="answer-card">
                            <div class="question">Question ID: {{ $qId }}</div>
                            <div class="answer">
                                @if($sessionNum === 4)
                                    <strong>File:</strong> {{ $answer['original_name'] ?? 'Candidate submission' }} <br>
                                    <span style="font-size: 0.8em; color: #666;">View online: {{ $answer['full_url'] }}</span>
                                @else
                                    {{ is_array($answer) ? implode(', ', $answer) : (is_array($answer) ? json_encode($answer) : $answer) }}
                                @endif
                            </div>
                        </div>
                    @endforeach
                @else
                    <p style="font-style: italic; color: #999; margin-left: 10px;">No answers recorded for this session.</p>
                @endif
            @endforeach
        @else
            <p>No answers recorded.</p>
        @endif
    </div>

    <div class="footer">
        Generated by Tako HR System on {{ date('d M Y, H:i') }}
    </div>
</body>
</html>
